/**
 * Scaredy Cat - Image model info
 * GENERATED by eval/bakeoff/promote.mjs from models/image-model.json; do not
 * edit by hand (eval/model-manifest-test.mjs checks the two agree). The
 * service worker reads it synchronously at start-up, so the verdict cache and
 * feedback reports use the shipped model's version before the offscreen
 * document has loaded. Loaded via importScripts.
 */

const ScaredyCatModelInfo = Object.freeze({ id: 'tinyclip-vit-40m-32-laion400m', version: 'tinyclip40m-fp16-head-v1' });
